AWSTemplateFormatVersion: "2010-09-09"
Description: A simple CloudFormation template

Parameters:
  MyBucketName:
    Type: String
    Description: Name of the S3 bucket

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref MyBucketName

Outputs:
  BucketNameOutput:
    Description: "The name of the S3 bucket"
    Value: !Ref MyBucket



//comment  in the filr